// AttackData.jsx

export const tactics = [
    {
        name: 'Initial Access',
        techniques: [
            'Drive-by Compromise',
            'Exploit Public-Facing Application',
            'Exploitation of Remote Services',
            'External Remote Services',
            'Internet Accessible Device',
            'Remote Services',
            'Replication Through Removable Media',
            'Rogue Master',
            'Spearphishing Attachment',
            'Supply Chain Compromise',
            'Transient Cyber Asset',
            'Wireless Compromise',
        ],
    },
    {
        name: 'Execution',
        techniques: [
            'Autorun Image',
            'Change Operating Mode',
            'Command-Line Interface',
            'Execution through API',
            'Graphical User Interface',
            'Hooking',
            'Modify Controller Tasking',
            'Native API',
            'Scripting',
            'User Execution',
        ],
    },
    {
        name: 'Persistence',
        techniques: [
            'Hardcoded Credentials',
            'Modify Program',
            'Module Firmware',
            'Project File Infection',
            'System Firmware',
            'Valid Accounts',
        ],
    },
    {
        name: 'Privilege Escalation',
        techniques: [
            'Exploitation for Privilege Escalation',
            'Hooking',
        ],
    },
    {
        name: 'Evasion',
        techniques: [
            'Change Operating Mode',
            'Exploitation for Evasion',
            'Indicator Removal on Host',
            'Masquerading',
            'Rootkit',
            'Spoof Reporting Message',
            'System Binary Proxy Execution',
        ],
    },
    {
        name: 'Discovery',
        techniques: [
            'Network Connection Enumeration',
            'Network Sniffing',
            'Remote System Discovery',
            'Remote System Information Discovery',
            'Wireless Sniffing',
        ],
    },
    {
        name: 'Lateral Movement',
        techniques: [
            'Default Credentials',
            'Exploitation of Remote Services',
            'Hardcoded Credentials',
            'Lateral Tool Transfer',
            'Program Download',
            'Remote Services',
            'Valid Accounts',
        ],
    },
    {
        name: 'Collection',
        techniques: [
            'Adversary-in-the-Middle',
            'Automated Collection',
            'Data from Information Repositories',
            'Data from Local System',
            'Detect Operating Mode',
            'I/O Image',
            'Monitor Process State',
            'Point & Tag Identification',
            'Program Upload',
            'Screen Capture',
            'Wireless Sniffing',
        ],
    },
    {
        name: 'Command and Control',
        techniques: [
            'Commonly Used Port',
            'Connection Proxy',
            'Standard Application Layer Protocol',
        ],
    },
    {
        name: 'Inhibit Response Function',
        techniques: [
            'Activate Firmware Update Mode',
            'Alarm Suppression',
            'Block Command Message',
            'Block Reporting Message',
            'Block Serial COM',
            'Change Credential',
            'Data Destruction',
            'Denial of Service',
            'Device Restart/Shutdown',
            'Manipulate I/O Image',
            'Modify Alarm Settings',
            'Rootkit',
            'Service Stop',
            'System Firmware',
        ],
    },
    {
        name: 'Impair Process Control',
        techniques: [
            'Brute Force I/O',
            'Modify Parameter',
            'Module Firmware',
            'Spoof Reporting Message',
            'Unauthorized Command Message',
        ],
    },
    {
        name: 'Impact',
        techniques: [
            'Damage to Property',
            'Denial of Control',
            'Denial of View',
            'Loss of Availability',
            'Loss of Control',
            'Loss of Productivity and Revenue',
            'Loss of Protection',
            'Loss of Safety',
            'Loss of View',
            'Manipulation of Control',
            'Manipulation of View',
            'Theft of Operational Information',
        ],
    },
];
